#!/usr/bin/env bash
#code to display number from 1 to 100 with fizz and buzz taking place of multiples of 3 and 5


for i in {1..100}
do
	if [ $((i%3)) == 0 ]; then
		if [ $((i%5)) == 0 ] ; then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $((i%5)) == 0 ]; then
		echo "Buzz"
	else
		echo $i
	fi
done
