#!/usr/bin/env bash
#Script displays best school other than the 4th and 8th iteration

a=1
while [ $a -le 10 ];
do
	if [ $a == 4 ]; then
		echo "bad luck"
		a=$((a+1))
	elif [ $a == 8 ]; then
		echo "good luck"
		a=$((a+1))
	else
		echo "Best School"
		a=$((a+1))
	fi
done
