#!/usr/bin/env bash
#script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# Without using pgrep
#third line must be # shellcheck disable=SC2009
./1-list_your_processes | grep "bash"
