#!/usr/bin/env bash
#This script displays to infinity and beyond indefinitely with sleep 2 in between eac iterartion and i am invincible when receiving a sigtem signal
trap 'echo "I am invincible!!!"' 15
while :
do
	echo"To infinity and beyond"
	sleep 2
done
